const fontFamily = {
  BlinkMacSystemFontLight: 'BlinkMacSystemFontLight',
  EncodeSansCondensedBlack: 'EncodeSansCondensedBlack',
  EncodeSansCondensedBold: 'EncodeSansCondensedBold',
  EncodeSansCondensedExtraBold: 'EncodeSansCondensedExtraBold',
  EncodeSansCondensedExtraLight: 'EncodeSansCondensedExtraLight',
  EncodeSansCondensedLight: 'EncodeSansCondensedLight',
  EncodeSansCondensedMedium: 'EncodeSansCondensedMedium',
  EncodeSansCondensedRegular: 'EncodeSansCondensedRegular',
  EncodeSansCondensedSemiBold: 'EncodeSansCondensedSemiBold',
  EncodeSansCondensedThin: 'EncodeSansCondensedThin',

  FuturaPTCondBold: 'FuturaPTCondBold',
  FuturaPTCondBoldObl: 'FuturaPTCondBoldObl',
  OpenSansCondBold: 'OpenSansCondBold',
  OpenSansCondLight: 'OpenSansCondLight',
  OpenSansCondLightItalic: 'OpenSansCondLightItalic',

  RobotoBlack: 'RobotoBlack',
  RobotoBlackItalic: 'RobotoBlackItalic',
  RobotoBold: 'RobotoBold',
  RobotoBoldItalic: 'RobotoBoldItalic',
  RobotoItalic: 'RobotoItalic',
  RobotoLight: 'RobotoLight',
  RobotoLightItalic: 'RobotoLightItalic',
  RobotoMedium: 'RobotoMedium',
  RobotoMediumItalic: 'RobotoMediumItalic',
  RobotoRegular: 'RobotoRegular',
  RobotoThin: 'RobotoThin',
  RobotoThinItalic: 'RobotoThinItalic',

  Segoeuithis: 'Segoeuithis',
  SegoeuiBold: 'SegoeuiBold',
  SegoeuiItalic: 'SegoeuiItalic',

  Inter_18ptBlack: 'Inter_18ptBlack',
  Inter_18ptBlackItalic: 'Inter_18ptBlackItalic',
  Inter_18ptBold: 'Inter_18ptBold',
  Inter_18ptBoldItalic: 'Inter_18ptBoldItalic',
  Inter_18ptExtraBold: 'Inter_18ptExtraBold',
  Inter_18ptExtraBoldItalic: 'Inter_18ptExtraBoldItalic',
  Inter_18ptExtraLight: 'Inter_18ptExtraLight',
  Inter_18ptExtraLightItalic: 'Inter_18ptExtraLightItalic',
  Inter_18ptItalic: 'Inter_18ptItalic',
  Inter_18ptLight: 'Inter_18ptLight',
  Inter_18ptLightItalic: 'Inter_18ptLightItalic',
  Inter_18ptMedium: 'Inter_18ptMedium',
  Inter_18ptMediumItalic: 'Inter_18ptMediumItalic',
  Inter_18ptRegular: 'Inter_18ptRegular',
  Inter_18ptSemiBold: 'Inter_18ptSemiBold',
  Inter_18ptSemiBoldItalic: 'Inter_18ptSemiBoldItalic',
  Inter_18ptThin: 'Inter_18ptThin',
  Inter_18ptThinItalic: 'Inter_18ptThinItalic',

  Inter_24ptBlack: 'Inter_24ptBlack',
  Inter_24ptBlackItalic: 'Inter_24ptBlackItalic',
  Inter_24ptBold: 'Inter_24ptBold',
  Inter_24ptBoldItalic: 'Inter_24ptBoldItalic',
  Inter_24ptExtraBold: 'Inter_24ptExtraBold',
  Inter_24ptExtraBoldItalic: 'Inter_24ptExtraBoldItalic',
  Inter_24ptExtraLight: 'Inter_24ptExtraLight',
  Inter_24ptExtraLightItalic: 'Inter_24ptExtraLightItalic',
  Inter_24ptItalic: 'Inter_24ptItalic',
  Inter_24ptLight: 'Inter_24ptLight',
  Inter_24ptLightItalic: 'Inter_24ptLightItalic',
  Inter_24ptMedium: 'Inter_24ptMedium',
  Inter_24ptMediumItalic: 'Inter_24ptMediumItalic',
  Inter_24ptRegular: 'Inter_24ptRegular',
  Inter_24ptSemiBold: 'Inter_24ptSemiBold',
  Inter_24ptSemiBoldItalic: 'Inter_24ptSemiBoldItalic',
  Inter_24ptThin: 'Inter_24ptThin',
  Inter_24ptThinItalic: 'Inter_24ptThinItalic',

  Inter_28ptBlack: 'Inter_28ptBlack',
  Inter_28ptBlackItalic: 'Inter_28ptBlackItalic',
  Inter_28ptBold: 'Inter_28ptBold',
  Inter_28ptBoldItalic: 'Inter_28ptBoldItalic',
  Inter_28ptExtraBold: 'Inter_28ptExtraBold',
  Inter_28ptExtraBoldItalic: 'Inter_28ptExtraBoldItalic',
  Inter_28ptExtraLight: 'Inter_28ptExtraLight',
  Inter_28ptExtraLightItalic: 'Inter_28ptExtraLightItalic',
  Inter_28ptItalic: 'Inter_28ptItalic',
  Inter_28ptLight: 'Inter_28ptLight',
  Inter_28ptLightItalic: 'Inter_28ptLightItalic',
  Inter_28ptMedium: 'Inter_28ptMedium',
  Inter_28ptMediumItalic: 'Inter_28ptMediumItalic',
  Inter_28ptRegular: 'Inter_28ptRegular',
  Inter_28ptSemiBold: 'Inter_28ptSemiBold',
  Inter_28ptSemiBoldItalic: 'Inter_28ptSemiBoldItalic',
  Inter_28ptThin: 'Inter_28ptThin',
  Inter_28ptThinItalic: 'Inter_28ptThinItalic',

  PoppinsBlack: 'PoppinsBlack',
  PoppinsBold: 'PoppinsBold',
  PoppinsExtraBold: 'PoppinsExtraBold',
  PoppinsExtraLight: 'PoppinsExtraLight',
  PoppinsLight: 'PoppinsLight',
  PoppinsMedium: 'PoppinsMedium',
  PoppinsRegular: 'PoppinsRegular',
  PoppinsSemiBold: 'PoppinsSemiBold',
  PoppinsThin: 'PoppinsThin',
};

const colors = {
  background: '#282828',
};

export const THEME = {
  fontFamily,
  colors,
} as const;
